### ISSUE TITLE
\\ or \

### ISSUE THREAD

**Issue by Mar4eli** [augustt198/latex2sympy#27]
Hello,

I have been checking your examples and LaTex and found out, that frac with single slash (\frac) doesn't work. At the same time \ \frac is working.
![screenshot_5](https://cloud.githubusercontent.com/assets/7045770/19113306/adf86d94-8b11-11e6-9086-411e8ef30463.png)

Meanwhile, \sum, \int_ , \infty, \sqrt, \pi (with single \) are working, but binom needs \ \ (and convert to binom*(k*n), instead of binomial(k,n) in sympy ).
So, what to use? If we should strictly use \\, add this please to the documentation.

**Comment by Mar4eli** [comment]
\int_ and \sum works.

**Comment by augustt198** [comment]
You need double backslashes because otherwise python will interpret `\f` as a special character. So when you write `\\f` python interprets it as `\f`. `\int` and `\sum` work because `\i` and `\s` are not special characters. You can read more about this here: https://docs.python.org/2.0/ref/strings.html

**Comment by Mar4eli** [comment]
Thanks,
would be great, if this info appears in documentation for lib.
